import { Button, VerticalBox , AboutSlint } from "std-widgets.slint";

export AppWindow := Window {
    width: 320px;
    height: 240px;
    property<int> counter: 42;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                request-increase-value();
            }
        }
        AboutSlint { }
     }
}
